-- Migration: Add German aliases to Master Ingredients
DO $$ 
BEGIN
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Pilsener Malz', 'Pilsner Malz']) WHERE name = 'Pilsner Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Pale Ale Malz']) WHERE name = 'Pale Ale Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Wiener Malz']) WHERE name = 'Vienna Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Münchner Malz']) WHERE name = 'Munich Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Weizenmalz', 'Weizen hell']) WHERE name = 'Wheat Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Weizen dunkel', 'Weizenmalz dunkel']) WHERE name = 'Dark Wheat Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Carapils', 'Cara Hell']) WHERE name = 'Carahell';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Caramünch', 'Cara München']) WHERE name = 'Caramunich';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Cara Pils']) WHERE name = 'Carapils';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Carafa 1', 'Carafa Type 1']) WHERE name = 'Carafa I';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Carafa 2', 'Carafa Type 2']) WHERE name = 'Carafa II';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Carafa 3', 'Carafa Type 3']) WHERE name = 'Carafa III';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Schokoladenmalz', 'Chocolate Malz']) WHERE name = 'Chocolate Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Farbmalz', 'Röstmalz', 'Schwarzes Malz']) WHERE name = 'Black Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Röstgerste']) WHERE name = 'Roasted Barley';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Melanoidinmalz']) WHERE name = 'Melanoidin Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Sauermalz']) WHERE name = 'Acidulated Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Roggenmalz']) WHERE name = 'Rye Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Hafermalz']) WHERE name = 'Oat Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Dinkelmalz']) WHERE name = 'Spelt Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Rauchmalz']) WHERE name = 'Smoked Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Spitzmalz', 'Brühmalz']) WHERE name = 'Chit Malt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Saazer', 'Žatecký poloraný červeňák']) WHERE name = 'Saaz';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Hallertauer Mittelfrüh']) WHERE name = 'Hallertau Mittelfrüh';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Tettnanger']) WHERE name = 'Tettnang';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Spalter Select', 'Spalt Select']) WHERE name = 'Spalter Select';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Northern Brewer', 'Nordbrauer']) WHERE name = 'Northern Brewer';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Willamette']) WHERE name = 'Willamette';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Willamette', 'Fuggle']) WHERE name = 'Fuggles';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['EKG', 'Golding', 'East Kent Goldings']) WHERE name = 'East Kent Golding';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Cascade', 'Kaskade']) WHERE name = 'Cascade';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Hallertauer Magnum', 'Magnum']) WHERE name = 'Magnum';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Hallertauer Perle', 'Perle']) WHERE name = 'Perle';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Hallertauer Tradition', 'Tradition']) WHERE name = 'Tradition';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Hallertauer Herkules', 'Herkules']) WHERE name = 'Herkules';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Mandarina', 'Mandarina Bavaria']) WHERE name = 'Mandarina Bavaria';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Hüll Melon', 'Hüll Melon']) WHERE name = 'Huell Melon';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Polaris']) WHERE name = 'Polaris';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Smaragd']) WHERE name = 'Smaragd';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Spalter']) WHERE name = 'Spalt';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Lublin']) WHERE name = 'Lubelski';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Amarillo']) WHERE name = 'Amarillo';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Amarillo']) WHERE name = 'Citra';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Mosaic']) WHERE name = 'Mosaic';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Simcoe']) WHERE name = 'Simcoe';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['SafAle US-05', 'American Ale']) WHERE name = 'US-05';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['SafAle S-04', 'English Ale']) WHERE name = 'S-04';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['SafLager W-34/70', 'Weihenstephan']) WHERE name = 'W34/70';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['SafLager S-23', 'Berlin']) WHERE name = 'S-23';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['SafAle WB-06', 'Wheat']) WHERE name = 'WB-06';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Nottingham Ale']) WHERE name = 'Nottingham';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Windsor Ale']) WHERE name = 'Windsor';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['London ESB Ale']) WHERE name = 'London ESB';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Belle Saison']) WHERE name = 'Belle Saison';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['West Coast Ale']) WHERE name = 'BRY-97';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Cask & Bottle Conditioning']) WHERE name = 'CBC-1';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['US West Coast', 'M44 US West Coast']) WHERE name = 'M44';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Liberty Bell Ale', 'M36 Liberty Bell']) WHERE name = 'M36';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Empire Ale', 'M15 Empire Ale']) WHERE name = 'M15';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Bavarian Wheat', 'M20 Bavarian Wheat']) WHERE name = 'M20';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Belgian Wheat', 'M21 Belgian Wheat']) WHERE name = 'M21';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['French Saison Ale', 'M29 French Saison Ale']) WHERE name = 'M29';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Belgian Ale', 'M41 Belgian Ale']) WHERE name = 'M41';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Belgian Abbey', 'M47 Belgian Abbey']) WHERE name = 'M47';
  UPDATE ingredient_master SET aliases = array_cat(COALESCE(aliases, ARRAY[]::TEXT[]), ARRAY['Belgian Strong', 'M54 Belgian Strong']) WHERE name = 'M54';
END $$;