-- Create and seed bjcp_styles table (idempotent)
-- Source: BJCP 2021 Style Guidelines

create table if not exists "public"."bjcp_styles" (
  "id"             uuid not null default gen_random_uuid(),
  "code"           text not null,
  "category"       text not null,
  "name_en"        text not null,
  "name_de"        text not null,
  "og_min"         numeric(5,4),
  "og_max"         numeric(5,4),
  "fg_min"         numeric(5,4),
  "fg_max"         numeric(5,4),
  "abv_min"        numeric(4,1),
  "abv_max"        numeric(4,1),
  "ibu_min"        integer,
  "ibu_max"        integer,
  "ebc_min"        integer,
  "ebc_max"        integer,
  "description_de" text,
  "ingredients_de" text,
  "examples"       text,
  "created_at"     timestamp with time zone default now(),
  "updated_at"     timestamp with time zone default now(),
  constraint "bjcp_styles_pkey" primary key ("id"),
  constraint "bjcp_styles_code_key" unique ("code")
);

alter table "public"."bjcp_styles" enable row level security;

create index if not exists "idx_bjcp_styles_code"     on "public"."bjcp_styles" using btree ("code");
create index if not exists "idx_bjcp_styles_category" on "public"."bjcp_styles" using btree ("category");

create or replace function public.set_updated_at_bjcp_styles()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists trg_bjcp_styles_updated_at on public.bjcp_styles;
create trigger trg_bjcp_styles_updated_at
  before update on public.bjcp_styles
  for each row execute function public.set_updated_at_bjcp_styles();

drop policy if exists "bjcp_styles_public_read" on "public"."bjcp_styles";
create policy "bjcp_styles_public_read" on "public"."bjcp_styles"
  for select using (true);

-- ─── Seed data ───────────────────────────────────────────────────────────────
insert into "public"."bjcp_styles"
  (code, category, name_en, name_de, og_min, og_max, fg_min, fg_max, abv_min, abv_max, ibu_min, ibu_max, ebc_min, ebc_max, description_de, ingredients_de, examples)
values
  ('1A',  'American Light Lager',           'American Light Lager',                   'Amerikanisches Helles Lager',          1.028, 1.040, 0.998, 1.008, 2.8,  4.2,   8,  12,  4,  6,  'Sehr helles, klares, sehr schwach gehopftes Bier. Kaum Malz- oder Hopfenaromen. Erfrischend und leicht. Sehr hohe Vergärungsgrade.',                     'Pilsnermalz, Mais oder Reis als Adjunkte, neutrale Lagerhefe',                                                                  'Bud Light, Coors Light, Miller Lite'),
  ('1B',  'American Lager',                 'American Lager',                         'Amerikanisches Lager',                 1.040, 1.050, 1.004, 1.010, 4.2,  5.3,   8,  18,  4,  8,  'Helles, klares Bier mit geringem Malzcharakter. Sehr geringe Hopfenbitterness. Sauber, crisp, erfrischend.',                                              'Pilsnermalz, Mais oder Reis, neutrale Lagerhefe',                                                                               'Budweiser, Corona Extra, Pabst Blue Ribbon'),
  ('3A',  'Czech Lager',                    'Czech Pale Lager',                       'Tschechisches Helles Lager',           1.028, 1.044, 1.008, 1.014, 3.0,  4.1,  20,  35,  6, 12,  'Schlankes, hopfenbetontes Bier mit weichem Malzkörper. Charakteristisches Saaz-Hopfenaroma. Sahnige Bitterness.',                                         'Bohemisches Pilsnermalz, Saaz-Hopfen, weiche böhmische Lagerhefe',                                                              'Budvar 11°, Březňák, Notch Session Pils'),
  ('3C',  'Czech Lager',                    'Czech Amber Lager',                      'Tschechisches Amber Lager',            1.044, 1.060, 1.013, 1.017, 4.4,  5.8,  20,  35, 20, 32,  'Malzbetont mit Karamell- und Brötchenaromen. Deutliche Saaz-Hopfenbitterness. Vollmundig mit weichem Abgang.',                                            'Pilsnermalz, Karamellmalz, Saaz, weiche böhmische Lagerhefe',                                                                   'Budvar 12° Dark, Bernard Amber 12°'),
  ('4C',  'Pale Malty European Lager',      'Helles Bock',                            'Helles Bock',                          1.064, 1.072, 1.013, 1.019, 6.3,  7.4,  23,  35, 12, 18,  'Malzreich, süßlich mit Brot- und Toastaromen. Geringe Hopfenbitterness. Klar, goldfarben. Kein Karamell.',                                                'Pilsnermalz, helles Münchnermalz, Noble Hops, Lagerhefe',                                                                       'Weihenstephaner Vitus, Paulaner Salvator (hell), Einbecker Maibock'),
  ('5A',  'Pale Bitter European Beer',      'German Leichtbier',                      'Deutsches Leichtbier',                 1.026, 1.034, 1.006, 1.010, 2.4,  3.6,  15,  28,  3,  8,  'Leicht, schlank, trocken. Geringe Malzsüße. Mäßige bis geringere Hopfenbitterness. Clean, crisper Charakter.',                                           'Pilsnermalz, helles Karamalz, Magnum/Hallertau, neutrale deutsche Lagerhefe',                                                   'Bitburger Light, Jever Light, Beck''s Light'),
  ('5B',  'Pale Bitter European Beer',      'Kölsch',                                 'Kölsch',                               1.044, 1.050, 1.007, 1.011, 4.4,  5.2,  18,  30,  7, 10,  'Zart-fruchtig, frisch, helles, von oben vergoren. Leichte Malzsüße und dezente Hopfenbitterness. Weinige Fruchtaromen.',                                 'Pilsnermalz, bis 20% Weizenmalz, Hallertau/Spalt, Kölsch-Hefe',                                                                'Reissdorf, Früh, Dom Kölsch, Gaffel'),
  ('5C',  'Pale Bitter European Beer',      'German Helles Exportbier',               'Deutsches Helles Export',              1.048, 1.056, 1.010, 1.015, 4.8,  6.0,  20,  30,  8, 14,  'Ausgewogen, Malz und Hopfen gleichmäßig. Weiche Maltigkeit, mäßige Hopfenbitterness. Vollmundiger als Helles.',                                          'Pilsnermalz, Hallertauer Noble Hops, Lagerhefe Bayern',                                                                         'Ayinger Export, Spaten Export'),
  ('5D',  'Pale Bitter European Beer',      'German Pils',                            'Deutsches Pils',                       1.044, 1.050, 1.008, 1.013, 4.4,  5.2,  22,  40,  4, 10,  'Trocken, hopfenbetont, clear und crispe Bitterness. Minimale Malzsüße. Deutliches Hopfenaroma (Noble Hops).',                                            'Pilsnermalz, Hallertau/Spalt/Tettnang Noble Hops, trockene Lagerhefe',                                                          'Jever Pils, König Pils, Bitburger, Warsteiner'),
  ('6A',  'Amber Malty European Lager',     'Märzenbier/Oktoberfest',                 'Märzenbier / Oktoberfest',             1.054, 1.060, 1.010, 1.014, 5.8,  6.3,  18,  24, 16, 34,  'Malzreich, vollmundig, Karamell- und Brotharomen. Sauber mit weicher Hopfenbitterness. Kupfer- bis bernsteinfarbig.',                                     'Wiener Malz, Münchnermalz, Noble Hops, bayerische Lagerhefe',                                                                   'Paulaner Urmarzen, Hacker-Pschorr Märzen, Ayinger Oktoberfest'),
  ('7A',  'Amber Bitter European Beer',     'Vienna Lager',                           'Wiener Lager',                         1.048, 1.055, 1.010, 1.014, 4.7,  5.5,  18,  30, 18, 30,  'Weich-malziges Bier mit Toast- und Karamellaroma. Mäßige Hopfenbitterness, sauber trocken. Kupfer- bis bernsteinfarben.',                                'Wiener Malz, Münchner Malz, Saaz/Hallertau, mittelfrische Lagerhefe',                                                           'Ottakringer Wiener Original, Negra Modelo, Devils Backbone Vienna'),
  ('8A',  'Dark European Lager',            'Munich Dunkel',                          'Münchner Dunkel',                      1.048, 1.056, 1.010, 1.016, 4.5,  5.6,  18,  28, 34, 55,  'Malzreich, Brot-, Nuss- und Schokoladenaromen. Geringe bis mäßige Hopfenbitterness. Vollmundig, sauber, trocken im Abgang.',                             'Münchner Dunkelmalz, Caramünch, Röstmalz, Hallertau, Münchner Lagerhefe',                                                       'Ayinger Altbairisch Dunkel, Hacker-Pschorr Münchner Dunkel, Weltenburger Kloster Asam Bock'),
  ('9A',  'Strong European Beer',           'Doppelbock',                             'Doppelbock',                           1.072, 1.112, 1.016, 1.024, 7.0, 10.0,  16,  26, 12, 50,  'Sehr malzreich, süßlich bis trocken. Karamell-, Toffee-, Dörrobst-Aromen. Geringe Hopfenbitterness. Vollmundig, wärmend.',                               'Münchnermalz, Pilsnermalz, Karamellmalze, Noble Hops, Münchner Lagerhefe',                                                      'Paulaner Salvator, Ayinger Celebrator, Weihenstephaner Korbinian'),
  ('9C',  'Strong European Beer',           'Baltic Porter',                          'Baltic Porter',                        1.060, 1.090, 1.016, 1.024, 6.5,  9.5,  20,  40, 34, 60,  'Komplex, dunkles Fruchtaroma (Pflaumen, Kirschen), Schokolade, Karamell. Mild hopfig. Wärmend mit weichem Körper.',                                     'Pilsnermalz, Münchnermalz, Karamellmalze, Röstmalz, Noble Hops, Lagerhefe',                                                     'Sinebrychoff Porter, Okocim Porter, Carnegie Stark Porter'),
  ('10A', 'German Wheat Beer',              'Weissbier',                              'Weißbier / Hefeweizen',                1.044, 1.052, 1.010, 1.014, 4.3,  5.6,   8,  15,  4, 12,  'Fruchtiger Bananenester und rauchige Gewürznelkencharakter. Trüb, cremig, hohe Kohlensäure. Weich und erfrischend.',                                     '50%+ Weizenmalz, Pilsnermalz, Hallertau, hefeweizen-typische Weizenhefe (WB-06 / W3068)',                                       'Weihenstephaner Hefeweissbier, Paulaner Hefe-Weißbier, Schneider Weisse Tap 7'),
  ('10B', 'German Wheat Beer',              'Dunkles Weissbier',                      'Dunkles Weißbier',                     1.044, 1.056, 1.010, 1.014, 4.3,  5.6,  10,  18, 28, 46,  'Dunkles Weizen mit Brot-, Karamell- und Bananennaromen. Vollmundiger als Hefeweizen. Charakteristische Weizenhefe-Ester.',                               '50%+ Weizenmalz, Münchnermalz, Röstmalz (gering), Weizenhefe',                                                                  'Erdinger Dunkel, Schneider Weisse Tap 5, Franziskaner Dunkel'),
  ('10C', 'German Wheat Beer',              'Weizenbock',                             'Weizenbock',                           1.064, 1.090, 1.015, 1.022, 6.5,  9.0,  15,  30, 12, 50,  'Starkes Weizenbier mit reifen Früchten (Banane, Vanille), Karamell. Komplex, wärmend, vollmundig. Wenig Hopfenbitterness.',                              'Weizenmalz, Münchnermalz, Karamellmalz, Weizenbockhefe (W3333)',                                                                'Schneider Aventinus, Ayinger Weizenbock, Weihenstephaner Vitus'),
  ('11A', 'British Bitter',                 'Ordinary Bitter',                        'Englisches Ordinary Bitter',           1.030, 1.039, 1.007, 1.011, 3.2,  3.8,  25,  35, 16, 28,  'Trocken hopfig, leicht bis mittlerer Körper. Erdige, blumige und zitrusartige Hopfenaromen. Cask-Charakter, keine starke Kohlensäure.',                  'British Pale Ale Malz, Crystal 60, British Hopfen (Fuggles/EKG), britische Ale-Hefe',                                          'Fuller''s Chiswick Bitter, Adnams Southwold Bitter, Young''s Bitter'),
  ('11B', 'British Bitter',                 'Best Bitter',                            'Englisches Best Bitter',               1.040, 1.048, 1.008, 1.012, 3.8,  4.6,  25,  40, 16, 32,  'Ausgewogen mit mehr Körper und Hopfencharakter als Ordinary Bitter. Fruchtiger Ester-Charakter, trockener Abgang.',                                      'British Pale Ale Malz, Crystal Malz, British Hopfen, britische Ale-Hefe mit mittlerer Vergärung',                               'Fuller''s London Pride, Adnams Broadside, Bass Ale'),
  ('12A', 'Pale Commonwealth Beer',         'British Golden Ale',                     'Britisches Golden Ale',                1.038, 1.053, 1.006, 1.012, 3.8,  5.0,  20,  45,  2, 12,  'Hell, fruchtig-hopfig, erfrischend. Moderne britische Hopfen (Cascade, Citra, Centennial möglich). Sauberer trockener Abgang.',                           'Britisches Pale Malz, helles Crystal, verschiedene Hopfensorten, britische Ale-Hefe',                                           'Exmoor Gold, Hop Back Summer Lightning, Crouch Vale Brewers Gold'),
  ('13A', 'Brown British Beer',             'Dark Mild',                              'Dark Mild',                            1.030, 1.038, 1.008, 1.013, 3.0,  3.8,  10,  25, 28, 50,  'Dunkel, malzreich, Karamell-, Toffee- und Schokoladenaromen. Geringer Hopfencharakter. Süßlicher Abgang, leichter Körper.',                              'British Pale Malz, Crystal 77, Röstgerste, britische Hopfen, englische Ale-Hefe',                                               'Moorhouse''s Black Cat, Theakston''s Mild, Sarah Hughes Dark Ruby'),
  ('14A', 'Scottish Ale',                   'Scottish Light',                         'Scottish Light 60/-',                  1.030, 1.035, 1.010, 1.013, 2.5,  3.2,  10,  20, 34, 50,  'Malzreich, geringe Hopfenbitterness. Karamell und leichte Nuss-Noten. Kein Rauch. Vollmundig trotz geringen Alkohols.',                                  'Scottish Pale Malz, Crystal 80, geringe Röstmalze, britische Hopfen, Scottish Ale-Hefe',                                        'McEwan''s 60/-, Belhaven Scottish Ale'),
  ('15A', 'Irish Beer',                     'Irish Red Ale',                          'Irish Red Ale',                        1.036, 1.046, 1.010, 1.014, 3.8,  5.0,  18,  28, 18, 28,  'Kupferrot, malzreich, leichte Caramel-Süße, röstiger Einschlag im Abgang. Geringe Hopfenbitterness. Sauber mit mittlerem Körper.',                       'Irish/British Pale Malz, Crystal 150, geringe Röstgerste, UK Hopfen, irische Ale-Hefe',                                         'Smithwick''s, Murphy''s Irish Red, Kilkenny'),
  ('15B', 'Irish Beer',                     'Irish Stout',                            'Irish Stout',                          1.036, 1.044, 1.007, 1.011, 4.0,  4.5,  25,  45, 50, 79,  'Trocken, röstiger Kaffeecharakter ohne Süße. Stickstoffkarbonisierung ergibt cremige Textur. Bitterness dominiert den Abgang.',                          'Pale Malz, Röstgerste (ungemälzt), Flaked Barley, UK Hopfen, Dry Stout Hefe',                                                   'Guinness Draught, Murphy''s Irish Stout, Beamish Irish Stout'),
  ('16A', 'Dark British Beer',              'Sweet Stout',                            'Sweet Stout / Milk Stout',             1.044, 1.060, 1.012, 1.024, 4.0,  6.0,  20,  40, 59, 79,  'Süßlich, cremig, Schokolade, Kaffee, Lakritze. Laktose erhöht Restsüße und Körper. Ausgeprägte Röstaromen ohne Schärfe.',                               'Pale Malz, Laktose, Chocolate Malz, Röstgerste, UK Hopfen, englische Ale-Hefe',                                                 'Mackeson XXX Stout, Left Hand Milk Stout, Wells Bombardier (dark)'),
  ('16C', 'Dark British Beer',              'Oatmeal Stout',                          'Oatmeal Stout',                        1.045, 1.065, 1.010, 1.018, 4.2,  5.9,  25,  40, 43, 79,  'Hafer verleiht seidigen, vollmundigen Körper. Kaffee, Schokolade, nussige Aromen. Mäßige Bitterness, milder Röstcharakter.',                             'Pale Malz, Hafermalz/Haferflocken (5-15%), Chocolate Malz, Röstmalz, UK Hopfen',                                                'Samuel Smith''s Oatmeal Stout, Anderson Valley Barney Flats, McAuslan St-Ambroise Oatmeal'),
  ('17A', 'Strong British Ale',             'British Strong Ale',                     'Britisches Strong Ale',                1.055, 1.080, 1.015, 1.022, 5.5,  8.0,  30,  60, 16, 36,  'Komplex, reiche Malzaromen, Karamell, Trockenobst, Gewürze. Kräftige aber ausgewogene Hopfenbitterness. Wärmend.',                                       'British Pale Malz, Crystal, invert Zucker, UK Hopfen, fruchtbildende englische Hefe',                                           'Fuller''s ESB, Adnams Broadside 6%, Young''s Special'),
  ('18A', 'Pale American Ale',              'Blonde Ale',                             'Blonde Ale',                           1.038, 1.054, 1.008, 1.013, 3.8,  5.5,  15,  28,  6, 12,  'Hell, zugänglich, ausgewogen. Geringe bis mäßige Malzsüße, keine Fruchtester. Sauber-erfrischend, sanfte Hopfennoten.',                                  'Pale 2-Row oder Pilsnermalz, US Hopfen, neutrale US Ale-Hefe',                                                                  'Kona Big Wave, Widmer Blonde, Sierra Nevada Summerfest'),
  ('18B', 'Pale American Ale',              'American Pale Ale',                      'American Pale Ale',                    1.045, 1.060, 1.010, 1.015, 4.5,  6.2,  30,  50, 10, 20,  'Hopfenbetont mit charakteristischen US Hopfenaromen (Zitrus, Kiefer, tropische Früchte). Moderater Malzkörper, trockener Abgang.',                       'American 2-Row, Crystal 40, Cascade/Centennial/Simcoe, US Ale-Hefe (1056, US-05)',                                              'Sierra Nevada Pale Ale, Deschutes Mirror Pond, Three Floyds Zombie Dust (light)'),
  ('19A', 'Amber and Brown American Beer',  'American Amber Ale',                     'American Amber Ale',                   1.045, 1.060, 1.010, 1.015, 4.5,  6.2,  25,  40, 20, 34,  'Ausgewogen zwischen Karamellmalz-Süße und US Hopfenaroma. Mittlerer Körper, Nuss und Toffee, angenehme Hopfenbitterness.',                               '2-Row, Crystal 40/80, US Hopfen (häufig Cascade/Centennial), US Ale-Hefe',                                                      'Bell''s Amber Ale, Deschutes Mirror Pond Amber, Full Sail Amber'),
  ('19B', 'Amber and Brown American Beer',  'California Common',                      'California Common / Steam Beer',       1.048, 1.054, 1.011, 1.014, 4.5,  5.5,  30,  45, 20, 28,  'Bernsteinfarben, toastig-malzig, stark von Northern Brewer-Hopfen (würzig-minzig). Vergoren mit Lagerhefe bei Ale-Temperaturen.',                        'American 2-Row oder Crystal, Northern Brewer Hopfen, California Lager Hefe (WLP810)',                                           'Anchor Steam Beer, Flying Dog Old Scratch Amber'),
  ('21A', 'IPA',                            'American IPA',                           'American IPA',                         1.056, 1.070, 1.008, 1.014, 5.5,  7.5,  40,  70, 12, 28,  'Hopfenbetont mit intensiven US Hopfenaromen (Zitrus, Kiefer, tropical). Mittlerer Malzkörper, trockener, bitter-langer Abgang.',                         '2-Row Pale Malz, Crystal 30-60, Cascade/Centennial/Chinook/Citra/Simcoe, US 1056',                                             'Bell''s Two Hearted, Dogfish Head 60 Minute, Founders Centennial IPA'),
  ('21B', 'IPA',                            'Specialty IPA: New England IPA',         'New England IPA (NEIPA / Hazy IPA)',   1.060, 1.085, 1.010, 1.015, 6.0,  9.0,  25,  60,  6, 14,  'Trüb, saftiger Fruchtcharakter (Mango, Pfirsich, Zitrus). Softer Körper durch Haze-Techniken. Geringere wahrnehmbare Bitterness trotz hoher IBU.',      'Pilsnermalz, Weizenmalz/Haferflocken (30%+), hohe Dry-Hop-Mengen (Citra, Mosaic, Galaxy, Sabro), hazy-fördernde Hefe',         'The Alchemist Heady Topper, Tree House Julius, Trillium Fort Point'),
  ('21C', 'IPA',                            'Specialty IPA: White IPA',               'White IPA',                            1.056, 1.065, 1.010, 1.016, 5.5,  7.0,  40,  70,  4,  8,  'Kombination von Weizen-Ale-Charakter und US IPA Hopfenaromen. Leicht treibig, fruchtig, würzig. Aromatische Kombi-Hefe typisch.',                        'Weizenmalz > 50%, 2-Row, US Hopfen (Citra/Galaxy), belgische oder Weizenhefe',                                                  'Blue Moon Brewing White IPA, Deschutes Chainbreaker'),
  ('22A', 'Strong American Ale',            'Double IPA',                             'Double / Imperial IPA (DIPA)',          1.065, 1.085, 1.008, 1.018, 7.5, 10.0,  60, 120, 12, 28,  'Intensiv hopfig, tropische Früchte und Kiefernharz dominieren. Starker Alkohol, dennoch trockener Körper. Extrem bitter.',                               '2-Row, minimale Crystal-Malze, hohe Hopfenmengen Citra/Simcoe/Chinook, clean US Hefe',                                          'Pliny the Elder, Stone Ruination, Dogfish Head 90 Minute'),
  ('22C', 'Strong American Ale',            'American Barleywine',                    'American Barleywine',                  1.080, 1.120, 1.016, 1.030, 8.0, 12.0,  50, 100, 20, 38,  'Sehr komplex, reiche Malzaromen, Karamell, Trockenfrüchte plus starke US Hopfenaromen. Wärmend, dick, balanciert durch Bitterness.',                    'American 2-Row, Crystal 60-120, hohe Hopfenaromasorten (Cascade/Centennial), US 1056',                                          'Anchor Old Foghorn, Sierra Nevada Bigfoot, Bell''s Third Coast'),
  ('24A', 'Belgian Ale',                    'Witbier',                                'Witbier / Weißbier (Belgisch)',         1.044, 1.052, 1.008, 1.012, 4.5,  5.5,   8,  20,  4,  8,  'Treibig, hell, würzig. Koriander und getrocknete Orangenschale. Leichte Weizensäure, weiche Cremung. Erfrischend trocken.',                              '>50% ungem. Weizen, Pilsnermalz, Hafer optional, Koriander, Bitterorangeschale, belgische Weizenhefe (WY3944)',                 'Hoegaarden, Blue Moon Belgian White, Ommegang Witte'),
  ('24B', 'Belgian Ale',                    'Belgian Pale Ale',                       'Belgisches Pale Ale',                  1.048, 1.054, 1.010, 1.014, 4.8,  5.5,  20,  30, 16, 28,  'Malzig-fruchtig, würzige belgische Hefe-Ester. Ausgewogen mit moderater Hopfenbitterness und fruchtigen Karamell-Noten.',                                'Belgian oder British Pale Malz, Crystal, belgische Hefe (Wyeast 3655), flämische Hopfen',                                       'De Koninck, Palm Speciale, Leffe Blonde'),
  ('25A', 'Strong Belgian Ale',             'Belgian Blond Ale',                      'Belgisches Blond Ale',                 1.062, 1.075, 1.008, 1.018, 6.0,  7.5,  15,  30,  8, 14,  'Hell, würzig-fruchtig, komplex. Pilzige/nussige Hefe-Ester, Honig und Vanilla. Trocken-süßes Finish. Wärmend.',                                         'Pilsnermalz, heller Rohrzucker (Kandis), belgische noble Hops, belgische Ale-Hefe (Leffe Strain)',                              'Leffe Blonde, Affligem Blonde, Grimbergen Blonde'),
  ('25B', 'Strong Belgian Ale',             'Saison',                                 'Saison',                               1.048, 1.065, 1.002, 1.012, 3.5,  9.0,  20,  35, 10, 28,  'Sehr trocken, hochvergoren. Würzig-fruchtig mit Pfeffer, Zitrus, Erd- und Blumenaromen. Hochkarbonisiert, erfrischend, komplex.',                        'Pilsnermalz, Weizen, Hafer, Gewürze optional, belgische Saison-Hefe (3724/3711), Noble + peppery Hops',                        'Saison Dupont, Fantôme Saison, Brooklyn Sorachi Ace'),
  ('25C', 'Strong Belgian Ale',             'Belgian Golden Strong Ale',              'Belgisches Golden Strong Ale',         1.070, 1.095, 1.005, 1.016, 7.5, 10.5,  22,  35,  6, 12,  'Hoch alkoholisch, hell, trocken. Fruchtig-würzige belgische Hefe-Ester. Gefährlich: Alkohol kaum wahrnehmbar durch trocken-sauberes Profil.',           'Pilsnermalz, Kandiszucker (hell, >20%), belgische Hopfen, Duvel-Hefe-Strain',                                                   'Duvel, Delirium Tremens, Piraat, Judas'),
  ('26A', 'Monastic Ale',                   'Belgian Single',                         'Belgisches Single / Patersbier',       1.044, 1.054, 1.004, 1.010, 4.8,  6.0,  25,  45,  6, 14,  'Einzigartiger Hopfencharakter mit würzigen belgischen Ester-Aromen. Trocken, vergoren. Leichteres Klosterbier.',                                         'Pilsnermalz, sehr geringe Malzvielfalt, belgische Hopfen, belgische Trappisten-Hefe',                                           'Westmalle Extra, Westvleteren Blonde'),
  ('26B', 'Monastic Ale',                   'Belgian Dubbel',                         'Belgisches Dubbel',                    1.062, 1.075, 1.008, 1.018, 6.0,  7.6,  15,  25, 20, 34,  'Dunkle Früchte (Pflaumen, Kirschen, Rosinen), Karamell, Schokolade. Würzige Hefe. Alkohol wärmend. Weicher, vollmundiger Körper.',                       'Pilsnermalz, dunkler Kandiszucker, Special B, belgische Trappisten/Abbaye Hefe',                                                'Westmalle Dubbel, Chimay Red, La Trappe Dubbel'),
  ('26C', 'Monastic Ale',                   'Belgian Tripel',                         'Belgisches Tripel',                    1.075, 1.085, 1.008, 1.014, 7.5,  9.5,  20,  40,  9, 14,  'Hell, stark, würzig und fruchtig. Hohe Vergärung durch Kandiszucker. Komplex mit Gewürznelken, Orangen, Honig. Trocken-sauber.',                         'Pilsnermalz, heller Kandiszucker (15-25%), belgische Trappisten-Hefe (WY3787), Styrian Goldings',                              'Westmalle Tripel, Chimay White, St. Bernardus Tripel'),
  ('26D', 'Monastic Ale',                   'Belgian Dark Strong Ale',                'Belgisches Dark Strong Ale / Quadrupel', 1.075, 1.110, 1.010, 1.024, 8.0, 12.0,  20,  35, 24, 43,  'Sehr komplex, reiches Dunkelfruchtig (Pflaumen, Feigen, Rosinen), Schokolade, Karamell. Wärmend, alkoholtragend, würzige Hefe.',                       'Pilsnermalz, dunkler Kandiszucker, Special B, Aromamalze, belgische Trappisten-Hefe',                                           'Westvleteren 12, St. Bernardus Abt 12, Rochefort 10'),
  ('27',  'Historical Beer',                'Historical Beer',                        'Historisches Bier',                    1.040, 1.110, 1.008, 1.030, 4.0, 11.0,  10,  70,  4, 79,  'Historische oder regionale Bierstile (Gose, Lichtenhainer, Roggenbier, etc.). Sehr unterschiedlich je nach Substil.',                                   'Substil-abhängig; oft Weizen, Roggen, Salz, Koriander, Lacto',                                                                  'Döllnitzer Ritterguts Gose, Westbrook Gose, Professor Fritz Briem Berliner Weisse'),
  ('28A', 'American Wild Ale',              'Brett Beer',                             'Brett Beer',                           1.045, 1.090, 1.004, 1.012, 4.5,  9.0,   0,  30,  4, 36,  'Komplex wilder Charakter durch Brettanomyces. Leder, Stall, Funk, Tropisches. Sehr trocken, hoch vergoren. Sauerheit möglich.',                         'Jede Malzbasis, Brettanomyces-Hefe, lange Lagerung',                                                                            'Orval, Boulevard Brewing Saison Brett, Logsdon Seizoen Bretta'),
  ('29A', 'Fruit Beer',                     'Fruit Beer',                             'Fruchtbier',                           1.040, 1.110, 1.006, 1.030, 3.0, 11.0,   5,  70,  4, 79,  'Fruchtcharakter der Zutat sollte dominant sein, harmonisch mit Bierprofil. Natürliche Fruchtaromen bevorzugt.',                                          'Beliebige Basismalze + frische/gefrorene/getrocknete Früchte oder Fruchtsaft',                                                  'Samuel Adams Cherry Wheat, New Glarus Raspberry Tart, Lindemans Framboise'),
  ('30A', 'Spice/Herb/Vegetable Beer',      'Spice, Herb, or Vegetable Beer',         'Gewürz-, Kräuter- oder Gemüsebier',    1.040, 1.110, 1.008, 1.028, 3.0, 11.0,   5,  70,  4, 79,  'Gewürze, Kräuter oder Gemüse müssen klar erkennbar sein, harmonisch im Gleichgewicht mit dem Bierprofil. Keine Gewürz-Dominanz.',                       'Jede Malzbasis + diverse Gewürze/Kräuter (Ingwer, Vanille, Zimt, usw.)',                                                        'Dogfish Head Festina Pêche, New Belgium Accumulation, Rogue Yellow Snow'),
  ('33A', 'Wood Beer',                      'Wood-Aged Beer',                         'Fassgelagertes Bier',                  1.040, 1.120, 1.008, 1.030, 4.0, 12.0,   5,  60,  4, 79,  'Fassnoten (Vanille, Kokos, Eiche, Tannin) müssen harmonisch integriert sein. Spirituosen-Aromen möglich (Whisky, Bourbon, Rum, Wein).',                 'Jedes Bier + Holzfässer oder Holzchips (Eiche dominant, aber Kirsche/Akazie möglich)',                                          'Great Divide Barrel Aged Yeti, Goose Island Bourbon County Stout, Firestone Anniversary')
on conflict (code) do update set
  category       = excluded.category,
  name_en        = excluded.name_en,
  name_de        = excluded.name_de,
  og_min         = excluded.og_min,
  og_max         = excluded.og_max,
  fg_min         = excluded.fg_min,
  fg_max         = excluded.fg_max,
  abv_min        = excluded.abv_min,
  abv_max        = excluded.abv_max,
  ibu_min        = excluded.ibu_min,
  ibu_max        = excluded.ibu_max,
  ebc_min        = excluded.ebc_min,
  ebc_max        = excluded.ebc_max,
  description_de = excluded.description_de,
  ingredients_de = excluded.ingredients_de,
  examples       = excluded.examples,
  updated_at     = now();
